# Generated by Django 4.1.1 on 2022-09-08 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип сделки',
                'verbose_name_plural': 'Типы сделок',
                'db_table': 'deal_type',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(db_index=True, max_length=10, null=True, unique=True, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Рейтинг контрагента',
                'verbose_name_plural': 'Рейтинги контрагентов',
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Название')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rating', verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'db_table': 'counterparty',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 16, 51, 577118, tzinfo=datetime.timezone.utc), verbose_name='Дата сделки')),
                ('amount', models.FloatField(default=0, verbose_name='Объем')),
                ('cost', models.FloatField(default=0, verbose_name='Цена')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 16, 51, 577422, tzinfo=datetime.timezone.utc), verbose_name='Начало поставки')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 9, 8, 13, 16, 51, 577434, tzinfo=datetime.timezone.utc), null=True, verbose_name='Конец поставки')),
                ('counterparty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.counterparty', verbose_name='Контрагент')),
                ('destination_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.place', verbose_name='Пункт поставки')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventory', verbose_name='Инструмент')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dealtype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deal',
                'unique_together': {('type', 'deal_date', 'destination_place')},
            },
        ),
    ]
